export default [
  {type: 'text', author: 'me', data: { text: "Why don't they have salsa on the table?"}, date:"21/12/2021 3:57pm" },
  {type: 'text', author: 'them',letters:"AZ",  is_chatbot: true, data: { text: 'What do you need salsa for?'}, date:"21/12/2021 3:57pm" },
  {type: 'text', author: 'me', data: { text: 'Salsa is now the number one condiment in America.'}, date:"21/12/2021 3:57pm" },
  {type: 'text', author: 'them',letters:"AZ",  is_chatbot: true, data: { text: "You know why? Because people like to say 'salsa.' 'Excuse me, do you have salsa?' 'We need more salsa.' 'Where is the salsa? No salsa?'"}, date:"21/12/2021 3:57pm" },
  {type: 'text', author: 'me', data: { text: "You know it must be impossible for a Spanish person to order seltzer and not get salsa. 'I wanted seltzer, not salsa.'"}, date:"21/12/2021 3:57pm" },
  {type: 'text', author: 'them',letters:"AZ",  is_chatbot: true, data: { text: "Don't you know the difference between seltzer and salsa?? You have the seltezer after the salsa!"}, date:"21/12/2021 3:57pm" },
  {type: 'text', author: 'me', data: { text: 'See, this should be a show. This is the show. '}, date:"21/12/2021 3:57pm" },
  {type: 'text', author: 'them',letters:"AZ",  is_chatbot: false, data: { text: 'What?'}, date:"21/12/2021 3:57pm" },
  {type: 'text', author: 'me', data: { text: 'This. Just talking.'}, date:"21/12/2021 3:57pm" },
  {type: 'text', author: 'them',letters:"AZ",  is_chatbot: false, data: { text: 'Yeah, right.'}, date:"21/12/2021 3:57pm" },
  {type: 'text', author: 'me', data: { text: "I'm really serious. I think that's a good idea. "}, date:"21/12/2021 3:57pm" },
  {type: 'text', author: 'them',letters:"AZ",  is_chatbot: false, data: { text: "Just talking? Well what's the show about?"}, date:"21/12/2021 3:57pm" },
  {type: 'audio', author: 'them',letters:"AZ",  is_chatbot: false, data: { url: "https://maldita.es/uploads/bulletin/audios/6094002d360af634267003.ogg"}, date:"21/12/2021 3:57pm" },
  {type: 'image', author: 'them',letters:"AZ",  is_chatbot: false, data: { url: "https://maldita.es/uploads/public/202102/20210301_cierresperimetrales%20%281%29.jpg"}, date:"21/12/2021 3:57pm" },
  {type: 'video', author: 'them',letters:"AZ",  is_chatbot: false, data: { url: "https://assets.wealize.digital/video/w_2048.mp4"}, date:"21/12/2021 3:57pm" },
  {type: 'audio', author: 'me', data: { url: "https://maldita.es/uploads/bulletin/audios/6094002d360af634267003.ogg"}, date:"21/12/2021 3:57pm" },
  {type: 'image', author: 'me', data: { url: "https://maldita.es/uploads/public/202102/20210301_cierresperimetrales%20%281%29.jpg"}, date:"21/12/2021 3:57pm" },
  {type: 'video', author: 'me', data: { url: "https://assets.wealize.digital/video/w_2048.mp4"}, date:"21/12/2021 3:57pm" },
  {type: 'text', author: 'me', data: { text: "It's about nothing."}, date:"21/12/2021 3:57pm"  },
  {type: 'text', author: 'them',letters:"AZ",  is_chatbot: true, data: { text: 'No story?'}, date:"21/12/2021 3:57pm"  },
  {type: 'text', author: 'me', data: { text: 'No forget the story. '}, date:"21/12/2021 3:57pm"  },
  {type: 'text', author: 'them',letters:"AZ", is_chatbot: true,  data: { text: "You've got to have a story."}, date:"21/12/2021 3:57pm"  },
  {type: 'emoji', author: 'me', data: { emoji: '😋'}, date:"21/12/2021 3:57pm"  },
  {type: 'text', author: 'them',letters:"AZ",  is_chatbot: true, data: { text: 'Tell me your story!' }, date:"21/12/2021 3:57pm" , quickReplies: [
    { type: 'text', author: 'me', data: { text: 'Should I?' } },
    { type: 'emoji', author: 'me', data: { emoji: '🙊' } },
  ]},
];
